<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.1/TweenMax.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.1/TimelineMax.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/wavify@1.0.0/wavify.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/wavify@1.0.0/jquery.wavify.js"></script>
<script src="assets/js/script.js"></script>
<script src="assets/js/circle.js"></script>
<script src="assets/js/animation.js"></script>
<script src="assets/js/timeline.js"></script>
<script src="assets/js/contact.js"></script>
<script src="assets/js/footer.js"></script>
<script src="assets/js/backToTop.js"></script> 
<script src="assets/js/quote.js"></script>
